#!/bin/bash

# constants
local -r \
  RED=1 \
  GREEN=2 \
  BLUE=4
# shellcheck disable=SC2034
local -r \
  DONE="$(colorize "  ok  " $GREEN)" \
  FAILED="$(colorize " fail " $RED)" \
  SKIPPED="$(colorize " skip " $BLUE)"
